# Generated by Django 3.1.3 on 2021-03-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210326_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='This is my awesome bio!', max_length=200),
        ),
    ]
